FROM apache/airflow:2.10.5-python3.12

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        docker.io \
        git \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    pyarrow==23.0.0 \
    yfinance \
    psycopg2-binary \
    dbt-postgres